[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/kubernetes"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.1"

[[override]]
    name = "github.com/spf13/cobra"
    branch = "master"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.14.8"